### ISSUE TITLE
Suggest a feed must be indexed by Feedly before showing in NewsCatchr 

### ISSUE THREAD

**Issue by strangel8p** [NewsCatchr/NewsCatchr#20]
NewsCatchr shows a nothingFound popup whenever it can't find a feed through the Feedly API, even if the feed is valid. I couldn't find a way to tell Feedly to index a feed without creating an account, so maybe the only way to deal with this is by suggesting the user the feed should have been indexed by Feedly previously, along with the nothingFound popup.

**Comment by jlelse** [comment]
Thank you for this tip!

**Comment by jlelse** [comment]
I'll replace the feedly API usage with something custom, because it's better not to rely on this API for various reasons.
